### ISSUE TITLE
Create build and run scripts

### ISSUE THREAD

**Issue by junrui-liu** [textproclab/lore-server#3]
Create shell scripts to automate the building and running of docker images. Include documentation.

**Comment by junrui-liu** [comment]
The script should build both phases.

**Comment by jgordon** [comment]
I asked you to write these scripts because I've always managed Docker containers with `build` and `run` scripts (typically very short shell scripts), but since we'll have multiple Docker containers, we may want to use docker-compose to manage them. 

I'll commit my basic Flask application to master soon, and it currently uses one Dockerfile for the Flask web server and a docker-compose.yml file that manages it, so it can be started with `docker-compose up` and stopped with `docker-compose down`.

I don't know which way will wind up being easiest, but I wanted to let you know that I'm considering this.

**Comment by junrui-liu** [comment]
Thanks for letting me know this!
